name: Automated Tests
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run API tests
        run: npm run test:api
        env:
          API_TEST_REPORT_PATH: test-reports/api-report.xml

      - name: Run UI tests
        run: npm run test:ui
        env:
          UI_TEST_REPORT_PATH: test-reports/ui-report.xml

      - name: Upload test reports
        uses: actions/upload-artifact@v2
        with:
          name: Test Reports
          path: test-reports
